name: "Build and Push Branch"
description: "Build and Push Branch"
inputs:
  branch_name:
    required: true
  dockerhub_token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Parsing Inputs and set Variables
      id: vars
      shell: bash
      run: echo "::set-output name=oss_branch_tag::oss-branch-$(git rev-parse --short ${{ inputs.branch_name }})"

    - uses: actions/setup-java@v1
      with:
        java-version: "17"

    - uses: actions/setup-node@v1
      with:
        node-version: "16.13.0"

    - name: Set up CI Gradle Properties
      run: |
        mkdir -p ~/.gradle/
        cat > ~/.gradle/gradle.properties <<EOF
        org.gradle.jvmargs=-Xmx8g -Xss4m --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
          --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
          --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
          --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
          --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
        org.gradle.workers.max=8
        org.gradle.vfs.watch=false
        EOF
      shell: bash

    - name: Build
      run: VERSION=${{ steps.vars.outputs.oss_branch_tag }} SUB_BUILD=PLATFORM ./gradlew build --scan
      shell: bash

    - name: Publish to Maven Local
      run: VERSION=${{ steps.vars.outputs.oss_branch_tag }} SUB_BUILD=PLATFORM ./gradlew publishToMavenLocal
      shell: bash

    - name: Login to Docker (on Master)
      uses: docker/login-action@v1
      with:
        username: airbytebot
        password: ${{ inputs.dockerhub_token }}

    - name: Push Docker Images
      run: |
        docker push airbyte/worker:${{ steps.vars.outputs.oss_branch_tag }}
        docker push airbyte/webapp:${{ steps.vars.outputs.oss_branch_tag }}
      shell: bash
